apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.3
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  key: keycloak-admin
                  name: keycloak-secret
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: keycloak-password
                  name: keycloak-secret
            - name: KC_DB
              value: postgres
            - name: KC_DB_USERNAME
              value: Database-user
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-db-password
                  name: keycloak-postgresdb-secret
            - name: KC_PROXY
              value: "edge"
            - name: KC_DB_URL
              value: jdbc:postgresql://IP-ADDRESS/keycloak
            - name: KC_LOG
              value: console
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi