pipeline {
    agent any
    stages {
        stage('clean_up') {
            steps{
                deleteDir()
            }
        }
        stage('clone_repo') {
            steps {
                sh 'git clone https://github.com/jenkins-docs/simple-java-maven-app.git'
            }
        }
        stage('build') {
            steps {
                dir('simple-java-maven-app') {
                    sh 'mvn clean install'
                }
            }
        }
        stage('test') {
            steps {
                dir('simple-java-maven-app') {
                    sh 'mvn test'
                }
            }
        }
    }
}
